---
title: "rolex web scraping"
author: "Jake Epstein"
date: "11/9/2019"
output: html_document
---

```{r}
library(rvest)
library(stringr)
library(dplyr)
library(ggplot2)
library(jsonlite)
library(httr)
library(purrr)
```


### Chronex

```{r}
numpages = 14
storage = vector(mode = "list", length = numpages)

url_base = "https://www.chronext.com/buy?limit=72&q=&sorting=&filter.brand=Rolex&page="

parse_html = function(url){
  read_html(url) %>%
    html_nodes(".product-tile__price , .product-tile__model , #main li") %>%
    html_text() %>%
    unlist()
}


for(i in 1:numpages){
  url = paste0(url_base, i)
  storage[[i]] = parse_html(url)
  
}


raw = storage %>% unlist()
```


```{r}

date = rep("2019-11-09", length(raw)/3)
type = rep(NA, length(raw)/3)
price = rep(NA, length(raw)/3)

for(j in 1:length(raw)){
  item = raw[[j]] %>% str_remove_all("\ ") %>% str_remove_all("\\\n")
  if (str_count(item, "Rolex") == 1){next}
  if (str_detect(item, ",")) {price[[ceiling(j/3)]] = item } 
  else {type[[ceiling(j/3)]] = item}
}


rolex = data.frame(date, type, "chronex_price" = price, stringsAsFactors = FALSE)


parse_price = function(price_vect){
  ans = rep(NA, length(price_vect))
  for(i in 1:length(price_vect)){
    price = price_vect[[i]]
    if(str_count(price, "\\$") == 1) {
      ans[i] = str_remove(price, "\\$") %>% 
        str_remove_all(",") %>%
        as.numeric()
    }
    else{
      split = strsplit(price, "\\$") 
      ans[i] = mean(split[[1]] %>%str_remove_all(",") %>% as.numeric(), na.rm=TRUE)
    }
  }
  return(ans)
}


rolex$chronex_price = rolex$chronex_price %>% parse_price()

rolex = rolex %>%
  group_by(type, date) %>%
  summarize(chronex_price = mean(chronex_price))
```



```{r, fig.height=3, fig.width=3}

ggplot(rolex, aes(x = reorder(type,price), y = price, fill = gender))+
  geom_bar(stat = "identity") +
  theme(legend.position = "none") +
  labs(y = "Price ($)", x = "Watch", fill = "Gender")+
  coord_flip() +
  theme_minimal()

```

### eBay
```{r}
appID = "JacobEps-find-PRD-e38876c40-df7498ec"
baseurl = "https://svcs.ebay.com/services/search/FindingService/v1?"
oppname = "findCompletedItems"


findCompletedItems = function(keywords, appID = "JacobEps-find-PRD-e38876c40-df7498ec", baseurl = "https://svcs.ebay.com/services/search/FindingService/v1?", oppname = "findCompletedItems", format = "JSON", npages = 10) {
  map_df(1:npages, function(i){
    bind_rows(fromJSON(paste0(baseurl,
               "OPERATION-NAME=", oppname,
               "&SERVICE-VERSION=1.0.0&SECURITY-APPNAME=", appID,
               "&RESPONSE-DATA-FORMAT=", format,
               "&REST-PAYLOAD&keywords=", keywords,
               "&entriesPerPage=", 100,
               "&pageNumber=", i)))
  })
}


rolex_raw = findCompletedItems(URLencode("rolex datejust"), npages = 20)

ebay = rolex_raw %>% bind_rows() %>% .$searchResult %>% bind_rows() %>% .$item %>% bind_rows()


price = map(1:nrow(ebay), function(i) ebay$sellingStatus[[i]] %>% unlist() %>% .[[2]] %>% as.numeric()) %>% unlist()
ebay = data.frame("item" = unlist(ebay$title),  "ebay_price" = price) %>%
  unique()


```





### StockX
```{r}
# numpages = 14
# storage = vector(mode = "list", length = numpages)
# 
# url_base = "https://stockx.com/rolex?page="
# 
# parse_html = function(url){
#   read_html(url) %>%
#     html_nodes("PrimaryText-sc-12c6bzb-0") %>%
#     html_text() %>%
#     unlist()
# }
# 
# 
# for(i in 1:numpages){
#   Sys.sleep(rexp(1))
#   url = paste0(url_base, i)
#   storage[[i]] = parse_html(url)
#   
# }
# 
# 
# raw = storage %>% unlist()
# 
# fromJSON("https://stockx.com/api/products/38f7c67c-a609-4c6e-a285-be2ea102bb21/activity?state=480&currency=USD&limit=10&page=1&sort=createdAt&order=DESC&country=US")


# products = data.frame(
#   item = c("Rolex DateJust 16013", "Rolex DateJust 116334", "Rolex DateJust 116334", "Rolex DateJust 116300", "Rolex DateJust 116334", "Rolex DateJust 116300", "Rolex DateJust 126300", "Rolex DateJust 116300"),
#   id = c("254f6e0a-41b1-4657-9642-8ea184603d88", "6b0d738f-97f8-4fa0-946e-7fa393860326", "38f7c67c-a609-4c6e-a285-be2ea102bb21", "44cd55c7-1dbc-4963-b19d-ea38c4ac9d17", "5b2b11bf-41a4-4773-b47c-9835940c7f85", "40d468db-fdb1-47f0-a6b5-f6fc7cae7974", "39f29b56-3bd6-410e-a2c3-ab7ada1a48dc", "cd5eaae1-f964-4f93-9bed-ebca800e05d6")) %>%
#   mutate(url = paste0("https://stockx.com/api/products/", id, "/activity?state=480&currency=USD&limit=100&page=1&sort=createdAt&order=DESC&country=US"))
# 
# 
# abc  = map(1:nrow(products), function(i){
#   Sys.sleep(rexp(1))
#   df_i = fromJSON(products$url[[i]])
#   return(df_i[[1]]$ProductActivity %>% as.data.frame())
# })
# 
# 
# first = abc[[1]]
# 
# rolexes = map_df(1:length(abc), function(i) abc[[i]]$ProductActivity %>% as.data.frame())
# 
# df = merge(rolexes, products, by.x = )
```


